### ISSUE TITLE
Escaped quotes break string highlighting

### ISSUE THREAD

**Issue by NPN** [dbrgn/pest.vim#1]
![string_escape_bug](https://user-images.githubusercontent.com/1497826/46454980-6e0b7080-c798-11e8-8a74-7ae3001cdca3.png)

In the example above, the class `avatar` and the backslash after it are not highlighted: (characters marked with a caret below)
```html
rule = { "<div class=\"avatar\"><p>some text</p></div>" }
                       ^^^^^^^
```
Escaped quotes are not taken into account, so the string is treated as two strings instead of one. The entire string should be highlighted in red.

Note that this does work correctly in the online editor, so perhaps the CodeMirror rules could be reused here.

**Comment by dbrgn** [comment]
Thanks for the report!

I'm not currently working on a Pest grammar, so this has low priority for me. But pull requests are welcome!
